export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_SUCCESS = 'GET_SUCCESS';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';
export const GET_ACTIVE_COURSES = 'GET_ACTIVE_COURSES';
export const GET_GUEST_COURSE_INFO = 'GET_GUEST_COURSE_INFO';
export const COURSE_INFO_LOADING = 'COURSE_INFO_LOADING';

//Course
export const GET_CURRENT_COURSES = 'GET_CURRENT_COURSES';
//Exercise
export const GET_EXERCISE_LIST = 'GET_EXERCISE_LIST';
export const GET_COMMENT = 'GET_COMMENT';
export const GET_EXERPOINT = 'GET_EXERPOINT';
//Quiz
export const GET_CURRENT_TESTQUIZ = 'GET_CURRENT_TESTQUIZ';
export const GET_QUIZ_DETAIL = 'GET_QUIZ_DETAIL';
export const GET_QUIZ_LIST = 'GET_QUIZ_LIST';
export const GET_QUIZ_SUBMISSTION = 'GET_QUIZ_SUBMISSTION';
export const QUIZ_LOADING = 'QUIZ_LOADING';
export const GET_QUIZ_DONE = 'GET_QUIZ_DONE';
export const IS_DO_QUIZ_LOADING = 'IS_DO_QUIZ_LOADING';

//Attendance
export const GET_PROFILE = 'GET_PROFILE';
export const GET_ATTENDANCE = 'GET_ATTENDANCE';
export const CLEAR_ATTENDANCE = 'CLEAR_ATTENDANCE';
//User
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_USERS = 'GET_USERS';
export const CLEAR_USER = 'CLEAR_USER';
export const SEARCH_STUDENT = 'SEARCH_STUDENT';
//Point
export const GET_POINT_COLUMNS = 'GET_POINT_COLUMNS';
export const POINT_LOADING = 'POINT_LOADING';
export const GET_STUDENT_POINT = 'GET_STUDENT_POINT';

//Schedule
export const GET_SCHEDULE = 'GET_SCHEDULE';
export const SCHEDULE_LOADING = 'SCHEDULE_LOADING';
export const GET_EVENT_SCHEDULE = 'GET_EVENT_SCHEDULE';
export const GET_EXER = 'GET_EXER';
export const GET_SUBMISSION = 'GET_SUBMISSION';
export const SUBMIT_LOADING = 'SUBMIT_LOADING';
export const GET_SUBMISSION2 = 'GET_SUBMISSION2';
export const DEL_SUBMISSION = 'DEL_SUBMISSION';
export const GET_STUDENT = 'GET_STUDENT';
export const GET_STUDENT_COURSES = 'GET_STUDENT_COURSES';
export const GET_STUDENT_ABSENT_LIST = 'GET_STUDENT_ABSENT_LIST';
export const GET_ALL_COURSES = 'GET_ALL_COURSES';
export const GET_COURSE_INFO = 'GET_COURSE_INFO';
export const GET_COURSE = 'GET_COURSE';
export const GET_MANAGE_COURSES = 'GET_MANAGE_COURSES';
export const GET_APPROVE_LIST_TEACHER = 'GET_APPROVE_LIST_TEACHER';
export const GET_APPROVE_LIST_STUDENT = 'GET_APPROVE_LIST_STUDENT';
export const EXERCISE_LOADING = 'EXERCISE_LOADING';
export const USERS_LOADING = 'USERS_LOADING';
export const COMMENT_LOADING = 'COMMENT_LOADING';
export const ATTENDANCE_LOADING = 'ATTENDANCE_LOADING';
export const GET_TODAY_ATTENDANCE = 'GET_TODAY_ATTENDANCE';
export const ALLCOURSE_LOADING = 'ALLCOURSE_LOADING';
export const GET_LESSON_LIST = 'GET_LESSON_LIST';
export const LESSON_LOADING = 'LESSON_LOADING';
export const GET_LESSON = 'GET_LESSON';
export const GET_LESSON_TOTAL_LIST = 'GET_LESSON_TOTAL_LIST';
export const GET_LESSON_IN_COURSE = 'GET_LESSON_IN_COURSE';
export const GET_LESSON_LIST_INFO = 'GET_LESSON_LIST_INFO';

export const GET_SCHOOL = 'GET_SCHOOL';
export const SCHOOL_LOADING = 'SCHOOL_LOADING';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const GET_REP_MAIL_INFO = 'GET_REP_MAIL_INFO';

export const GET_ACCOUNTS = 'GET_ACCOUNTS';
export const ACCOUNTS_LOADING = 'ACCOUNTS_LOADING';
export const GET_ACCOUNT = 'GET_ACCOUNT';
export const GET_STUDENT_ACCOUNTS = 'GET_STUDENT_ACCOUNTS';

export const GET_MY_RATING = 'GET_MY_RATING';
export const GET_MY_TEACHER_RATING = 'GET_MY_TEACHER_RATING';
export const RATING_LOADING = 'RATING_LOADING';
export const GET_TEACHERS_RATING = 'GET_TEACHERS_RATING';
export const TEACHER_RATING_LOADING = 'TEACHER_RATING_LOADING';
export const GET_TEACHER_RATING = 'GET_TEACHER_RATING';


//infrastructure
export const GET_LIST_INFRASTRUCTURE = 'GET_LIST_INFRASTRUCTURE';
export const GET_INFRASTRUCTURE = 'GET_INFRASTRUCTURE';
export const GET_INFRASTRUCTURE_BY_ID = 'GET_INFRASTRUCTURE_BY_ID';

export const STATISTIC_LOADING = 'STATISTIC_LOADING';
export const GET_STATISTIC = 'GET_STATISTIC';
export const GET_MY_STATISTIC = 'GET_MY_STATISTIC';
export const MY_STATISTIC_LOADING = 'MY_STATISTIC_LOADING';

// quiz bank
export const QUIZ_BANK_LOADING = 'QUIZ_BANK_LOADING';
export const GET_QUIZBANK = 'GET_QUIZBANK';
export const GET_CATEGORY = 'GET_CATEGORY';

// submission
export const MY_SUBMISSION_LOADING = 'MY_SUBMISSION_LOADING';
export const GET_MY_SUBMISSION = 'GET_MY_SUBMISSION';

export const MY_SUBMISSION_QUIZ_LOADING = 'MY_SUBMISSION_QUIZ_LOADING';
export const GET_MY_SUBMISSION_QUIZ = 'GET_MY_SUBMISSION_QUIZ';