export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_SUCCESS = 'GET_SUCCESS';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';
export const GET_ACTIVE_COURSES = 'GET_ACTIVE_COURSES';
export const GET_GUEST_COURSE_INFO = 'GET_GUEST_COURSE_INFO';

//Course
export const GET_CURRENT_COURSES = 'GET_CURRENT_COURSES';
//Exercise
export const GET_EXERCISE_LIST = 'GET_EXERCISE_LIST';
export const GET_COMMENT = 'GET_COMMENT';
export const GET_EXERPOINT = 'GET_EXERPOINT';
//Quiz
export const GET_CURRENT_TESTQUIZ = 'GET_CURRENT_TESTQUIZ';
export const GET_QUIZ_DETAIL = 'GET_QUIZ_DETAIL';
export const GET_QUIZ_LIST = 'GET_QUIZ_LIST';
export const GET_QUIZ_SUBMISSTION = 'GET_QUIZ_SUBMISSTION';
export const QUIZ_LOADING = 'QUIZ_LOADING';
export const GET_QUIZ_DONE = 'GET_QUIZ_DONE';
export const IS_DO_QUIZ_LOADING = 'IS_DO_QUIZ_LOADING';

//Attendance
export const GET_PROFILE = 'GET_PROFILE';
export const GET_ATTENDANCE = 'GET_ATTENDANCE';
export const CLEAR_ATTENDANCE = 'CLEAR_ATTENDANCE';
//User
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_USERS = 'GET_USERS';
export const CLEAR_USER = 'CLEAR_USER';
//Point
export const GET_POINT_COLUMNS = 'GET_POINT_COLUMNS';
export const POINT_LOADING = 'POINT_LOADING';
export const GET_STUDENT_POINT = 'GET_STUDENT_POINT';

//Schedule
export const GET_SCHEDULE = 'GET_SCHEDULE';
export const SCHEDULE_LOADING = 'SCHEDULE_LOADING';
export const GET_EVENT_SCHEDULE = 'GET_EVENT_SCHEDULE';
export const GET_EXER = 'GET_EXER';
export const GET_SUBMISSION = 'GET_SUBMISSION';
export const SUBMIT_LOADING = 'SUBMIT_LOADING';
export const GET_SUBMISSION2 = 'GET_SUBMISSION2';
export const DEL_SUBMISSION = 'DEL_SUBMISSION';
export const GET_STUDENT = 'GET_STUDENT';
export const GET_STUDENT_COURSES = 'GET_STUDENT_COURSES';
export const GET_STUDENT_ABSENT_LIST = 'GET_STUDENT_ABSENT_LIST';
export const GET_ALL_COURSES = 'GET_ALL_COURSES';
export const GET_COURSE_INFO = 'GET_COURSE_INFO';
export const GET_MANAGE_COURSES = 'GET_MANAGE_COURSES';
export const GET_APPROVE_LIST_TEACHER = 'GET_APPROVE_LIST_TEACHER';
export const GET_APPROVE_LIST_STUDENT = 'GET_APPROVE_LIST_STUDENT';
export const EXERCISE_LOADING = 'EXERCISE_LOADING';
export const USERS_LOADING = 'USERS_LOADING';
export const COMMENT_LOADING = 'COMMENT_LOADING';
export const ATTENDANCE_LOADING = 'ATTENDANCE_LOADING';
export const GET_TODAY_ATTENDANCE = 'GET_TODAY_ATTENDANCE';
export const ALLCOURSE_LOADING = 'ALLCOURSE_LOADING';
export const GET_LESSON_LIST = 'GET_LESSON_LIST';
export const LESSON_LOADING = 'LESSON_LOADING';
export const GET_LESSON = 'GET_LESSON';
export const GET_LESSON_TOTAL_LIST = 'GET_LESSON_TOTAL_LIST';
export const GET_LESSON_IN_COURSE = 'GET_LESSON_IN_COURSE';

export const GET_SCHOOL = 'GET_SCHOOL';
export const SCHOOL_LOADING = 'SCHOOL_LOADING';
export const GET_PAY_URL = 'GET_PAY_URL';
export const CLEAR_URL = 'CLEAR_URL';
export const GET_VNPAY_RETURN = 'GET_VNPAY_RETURN';
export const CLEAR_VNPAY_RETURN = 'CLEAR_VNPAY_RETURN';
export const COURSE_INFO_LOADING = 'COURSE_INFO_LOADING';

export const GET_RATING = 'GET_RATING';
export const RATING_LOADING = 'RATING_LOADING';

//infrastructure
export const GET_INFRASTRUCTURE = 'GET_INFRASTRUCTURE';
export const GET_INFRASTRUCTURE_BY_ID = 'GET_INFRASTRUCTURE_BY_ID';